### ISSUE TITLE
Ophalen van posts zonder content

### ISSUE THREAD

**Issue by sdrenth** [Oetzie/SocialMedia#2]
In sommige gevallen wil je bijv. wel posts ophalen zonder content (bijv. instagram posts). Momenteel is dit nog niet mogelijk.

In ons geval moesten posts van Instagram zonder content wel getoond worden, dit heb ik als volgt opgelost:

```
$c->where(
	array(
		'active' => 1
	)
);

$c->where(
	array(
		array(
			'content:!=' => '',
			'source:!='  => 'instagram',
			array(
				'OR:source:='	=> 'instagram'
			)
		)
	)
);
```

**Comment by Oetzie** [comment]
Fixed in 1.1.1 aan de hand system setting per source
